'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
   
    await queryInterface.bulkInsert(
      "Hotels",
      [
        {
          productId: 9,
          stay: '2 noches',
          passengers: 2,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 1,
          price : 700,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 10,
          stay: '2 noches',
          passengers: 3,
          wifi: true,
          breakfast: false,
          parking: true,
          checkInWeb: true,
          agencyId: 1,
          price : 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 11,
          stay: '3 noches',
          passengers: 1,
          wifi: true,
          breakfast: true,
          parking: true,
          checkInWeb: true,
          agencyId: 1,
          price : 350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 12,
          stay: '2 noches',
          passengers: 4,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: false,
          agencyId: 1,
          price : 300,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 9,
          stay: '3 noches',
          passengers: 2,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 2,
          price : 900,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 10,
          stay: '2 noches',
          passengers: 3,
          wifi: true,
          breakfast: false,
          parking: true,
          checkInWeb: true,
          agencyId: 2,
          price : 550,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 11,
          stay: '1 noches',
          passengers: 1,
          wifi: true,
          breakfast: true,
          parking: true,
          checkInWeb: true,
          agencyId: 2,
          price : 150,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 12,
          stay: '2 noches',
          passengers: 4,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: false,
          agencyId: 2,
          price : 320,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 9,
          stay: '2 noches',
          passengers: 2,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 3,
          price : 700,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 10,
          stay: '2 noches',
          passengers: 3,
          wifi: true,
          breakfast: true,
          parking: true,
          checkInWeb: false,
          agencyId: 3,
          price :450,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 11,
          stay: '3 noches',
          passengers: 1,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 3,
          price : 310,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 12,
          stay: '2 noches',
          passengers: 4,
          wifi: true,
          breakfast: false,
          parking: false,
          checkInWeb: false,
          agencyId: 3,
          price : 280,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 9,
          stay: '2 noches',
          passengers: 2,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 4,
          price : 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 10,
          stay: '2 noches',
          passengers: 3,
          wifi: true,
          breakfast: true,
          parking: true,
          checkInWeb: false,
          agencyId: 4,
          price :350,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 11,
          stay: '3 noches',
          passengers: 1,
          wifi: true,
          breakfast: true,
          parking: false,
          checkInWeb: true,
          agencyId: 4,
          price : 210,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          productId: 12,
          stay: '2 noches',
          passengers: 4,
          wifi: true,
          breakfast: false,
          parking: false,
          checkInWeb: false,
          agencyId: 4,
          price : 180,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    );
  },

  async down (queryInterface, Sequelize) {
    
     await queryInterface.bulkDelete('Hotels', null, {});
     
  }
};
